### ISSUE TITLE
Some packages missing from docs.mirage.io

### ISSUE THREAD

**Issue by rymdhund** [mirage/docs#1]
I saw that some packages that are in the `PACKAGES` list are missing from docs.mirage.io. For example `mirage-types`.

I was trying to build the documentation to see if I could find the problem but opam couldn't find a solution for the packages. What switch are you targeting?

**Comment by avsm** [comment]
I think you might have caught the repo just as I was upgrading to a new version of odoc.  There should be a significantly larger number of packages up there now ... please reopen if not.
