### ISSUE TITLE
docs.mirage.io is 404

### ISSUE THREAD

**Issue by r14c** [mirage/docs#4]
my friend linked me to https://mirage.io and i followed one of the links to https://docs.mirage.io only to find a 404. you should be able to reproduce by clicking that link.

**Comment by r14c** [comment]
upon [further inspection](https://docs.mirage.io/base64/) if looks like what's missing is `/index.html`

**Comment by hannesm** [comment]
thanks for your report, @dinosaure fixed the link which now has the index page.
